using AiryBotCode.Application.Interfaces;
using AiryBotCode.Domain.database;
using AiryBotCode.Infrastructure.Database.Persistence.Config;
using AiryBotCode.Infrastructure.Database.Seeders;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace AiryBotCode.Infrastructure.Database.Persistence
{
    public class AIDbContext : DbContext
    {
        public AIDbContext(DbContextOptions<AIDbContext> options) : base(options) {
        }

        public DbSet<BotSetting> BotSettings { get; set; }
        public DbSet<GiveAwayUser> GiveAwayUsers { get; set; }
        public DbSet<CommandSetting> CommandSettings { get; set; }
        public DbSet<BotCommand> BotCommands { get; set; }
        public DbSet<ChannelWebhook> ChannelWebhooks { get; set; }
        public DbSet<UserConsent> UserConsents { get; set; }
        public DbSet<LevelUser> LevelUsers { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new BotSettingConfiguration());
            modelBuilder.ApplyConfiguration(new GiveAwayUserConfiguration());
            modelBuilder.ApplyConfiguration(new CommandSettingConfiguration());
            modelBuilder.ApplyConfiguration(new BotCommandConfiguration());
            modelBuilder.ApplyConfiguration(new ChannelWebhookConfiguration());
            modelBuilder.ApplyConfiguration(new UserConsentConfiguration());
            modelBuilder.ApplyConfiguration(new LevelUserConfiguration());
        }

        public static  IServiceCollection registerDbContext(IServiceCollection services)
        {
            // Construct the connection string directly from IConfiguration
            IConfigurationReader _config = services.BuildServiceProvider().GetRequiredService<IConfigurationReader>();
            string connectionString = _config.GetDatabaseConnectionString();

            if (string.IsNullOrWhiteSpace(_config.GetDatabaseHost()))
                throw new InvalidOperationException("Database configuration 'Host' is missing from appsettings.json.");
            services.AddDbContext<AIDbContext>(options =>
                options.UseNpgsql(connectionString));
            Console.WriteLine($"[DATABASE] Connecting to database... '{string.Join(";", connectionString.Split(';').Take(2))}'");

            // Test database connection.
            TestDbConnection(services);
            SeedData(services.BuildServiceProvider()).Wait();
            return services;
        }

        private static async Task SeedData(IServiceProvider serviceProvider)
        {
            try
            {
                await BotSettingsSeeder.Seed(serviceProvider);
            }
            catch (Exception ex) { }
        }

        // Self-heal for tables added to the model after the database already existed
        // (EnsureCreated skips them; this project uses no EF migrations). Idempotent —
        // IF NOT EXISTS — so it's a safe no-op once the table is present. Column types
        // match EF/Npgsql exactly: ulong → numeric(20,0), DateTime(UtcNow) → timestamptz,
        // int Id → identity; unique index name matches the entity configuration.
        public static void EnsureNewerTables(AIDbContext db)
        {
            const string sql = @"
                CREATE TABLE IF NOT EXISTS ""UserConsents"" (
                    ""Id""         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""BotId""      numeric(20,0) NOT NULL,
                    ""UserId""     numeric(20,0) NOT NULL,
                    ""AcceptedAt"" timestamp with time zone NOT NULL
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_UserConsents_BotId_UserId""
                    ON ""UserConsents"" (""BotId"", ""UserId"");

                -- Per-bot server-side image theme (columns added after the table
                -- already existed; EnsureCreated won't add them). Idempotent.
                ALTER TABLE ""BotSettings"" ADD COLUMN IF NOT EXISTS ""ThemeImage"" text;
                ALTER TABLE ""BotSettings"" ADD COLUMN IF NOT EXISTS ""ThemeData"" text;

                -- Leveling: global (cross-server) XP, one row per bot+user.
                CREATE TABLE IF NOT EXISTS ""LevelUsers"" (
                    ""Id""       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""BotId""    numeric(20,0) NOT NULL,
                    ""UserId""   numeric(20,0) NOT NULL,
                    ""UserName"" text NOT NULL DEFAULT '',
                    ""Xp""       bigint NOT NULL DEFAULT 0,
                    ""Level""    integer NOT NULL DEFAULT 0,
                    ""LastXpAt"" timestamp with time zone NOT NULL DEFAULT now()
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_LevelUsers_BotId_UserId""
                    ON ""LevelUsers"" (""BotId"", ""UserId"");";
            try
            {
                db.Database.ExecuteSqlRaw(sql);
                Console.WriteLine("- Ensured UserConsents + LevelUsers tables + BotSettings theme columns.");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"- EnsureNewerTables failed (non-fatal): {ex.Message}");
            }
        }

        private static void TestDbConnection(IServiceCollection services)
        {
            using (var provider = services.BuildServiceProvider())
            using (var scope = provider.CreateScope())
            {
                var db = scope.ServiceProvider.GetRequiredService<AIDbContext>();
                try
                {
                    if (db.Database.CanConnect())
                    {
                        Console.WriteLine("- DB Connected!");
                        db.Database.EnsureCreated(); // This creates tables if they don't exist
                        Console.WriteLine("- Tables created or already exist.");
                        // EnsureCreated() is a no-op on an ALREADY-existing database, so any
                        // table added to the model after the DB was first created is never
                        // made (this project has no migrations). Create those explicitly +
                        // idempotently here so e.g. the consent gate can actually record.
                        EnsureNewerTables(db);
                    }
                    else
                    {
                        Console.WriteLine("- DB Connection Failed!");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"- DB Connection Failed with exception: {ex.Message}");
                }
            }
        }
    }
}
